# Generated by Django 3.2.7 on 2021-09-18 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome completo')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('bairro', models.CharField(max_length=100, verbose_name='Bairro')),
                ('rua', models.CharField(max_length=100, verbose_name='Rua')),
                ('numero', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=100, verbose_name='Complemento')),
                ('pizza', models.CharField(choices=[('Pizza calabresa R$ 50,00', 'Pizza calabresa R$ 50,00'), ('Pizza Portuguesa R$ 50,00', 'Pizza Portuguesa R$ 50,00'), ('Pizza de Muçarela R$ 50,00', 'Pizza de Muçarela R$ 50,00'), ('Pizza Marguerita R$ 50,00', 'Pizza Marguerita R$ 50,00'), ('Pizza Quatro queijos R$ 50,00', 'Pizza Quatro queijos R$ 50,00')], max_length=100, verbose_name='Escolha seu sabor')),
            ],
        ),
    ]
